/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "vuepress-theme-nine",
  "description": "nine's homepage",
  "base": "/",
  "pages": [
    {
      "frontmatter": {
        "layout": "home"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-6767f14b",
      "path": "/",
      "lastUpdated": "4/18/2019, 4:59:17 PM",
      "type": "page"
    },
    {
      "title": "posts",
      "frontmatter": {
        "layout": "posts"
      },
      "regularPath": "/posts/",
      "relativePath": "posts/README.md",
      "key": "v-f4f4af7a",
      "path": "/posts/",
      "lastUpdated": "4/18/2019, 4:59:17 PM",
      "type": "page"
    },
    {
      "frontmatter": {
        "title": "Home",
        "layout": "Home"
      },
      "regularPath": "/",
      "key": "v-b2754d56",
      "path": "/",
      "type": "page"
    },
    {
      "frontmatter": {
        "title": "Posts",
        "layout": "Posts"
      },
      "regularPath": "/posts/",
      "key": "v-1f814451",
      "path": "/posts/",
      "type": "page"
    },
    {
      "frontmatter": {
        "title": "Tags",
        "layout": "Tags"
      },
      "regularPath": "/posts/tags/",
      "key": "v-03721585",
      "path": "/posts/tags/"
    },
    {
      "frontmatter": {
        "title": "Categories",
        "layout": "Categories"
      },
      "regularPath": "/posts/categories/",
      "key": "v-5eb9e6bc",
      "path": "/posts/categories/"
    }
  ],
  "themeConfig": {
    "personalInfo": {
      "nickname": "nine",
      "description": "Coder",
      "email": "wangjia_1919@163.com",
      "location": "sz",
      "organization": "",
      "avator": "https://www.meteorlxy.cn/assets/img/avator.jpg",
      "sns": {
        "github": {
          "account": "NineSwordsMonster",
          "link": "https://github.com/NineSwordsMonster"
        }
      }
    },
    "headerBackground": {
      "useGeo": true
    },
    "lastUpdated": true,
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "exact": true
      },
      {
        "text": "Posts",
        "link": "/posts/",
        "exact": false
      },
      {
        "text": "More Pages",
        "link": "/more-pages/",
        "exact": false
      }
    ],
    "comments": {
      "owner": "NineSwordsMonster",
      "repo": "vuepress-theme-nine",
      "clientId": "",
      "clientSecret": ""
    },
    "lang": {
      "home": "Home",
      "posts": "Posts",
      "category": "Category",
      "categories": "Categories",
      "tag": "Tag",
      "tags": "Tags",
      "allCategories": "All",
      "search": "Search",
      "searchHint": "Search in title and excerpt",
      "noRelatedPosts": "No related posts",
      "top": "Top",
      "createdAt": "Created",
      "updatedAt": "Updated",
      "prevPost": "Previous Post",
      "nextPost": "Next Post",
      "toc": "Table of Contents",
      "comments": "Comments",
      "notFound": "Oops ! The page is not here"
    },
    "defaultPages": {},
    "header": {
      "background": {}
    },
    "plugins": {}
  }
}